blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Read the Contributing Guidelines
    url: https://github.com/CharmAIOS/Charm/blob/main/CONTRIBUTING.md
    about: Please review this before submitting an issue.
  - name: ðŸ’¬ Join our Discord
    url: https://discord.gg/gdakynHUEb
    about: Ask questions and chat with the team.
